import type { Row } from "./parse.js";
import type { ColumnProfile } from "./profile.js";
import type { SchemaMap, Semantic, SemanticRule } from "./schema.js";
import { detectSchema } from "./schema.js";
import * as A from "./analytics.js";
export type MetricKind="sum"|"ratio"|"distinct"|"count"|"avg";
export interface PackMetric{id:string;label:string;kind:MetricKind;compute:(rows:Row[],s:SchemaMap)=>number;words:string[];format:"money"|"number"|"percent";builtin?:boolean;}
export interface KpiDef{key:string;label:string;icon:string;format:"money"|"number"|"percent";tooltip?:string;noChange?:boolean;value:(rows:Row[],s:SchemaMap)=>number;}
export interface RankSectionDef{dimension:Semantic;metric:"revenue"|"profit"|"quantity"|"orders";title:string;subtitle:string;emptyText:string;format:"money"|"number";limit:number;}
export interface CompositionDef{dimension:Semantic;fallback?:Semantic;title:string;subtitle:string;centerLabel:string;}
export interface IndustryPack{id:string;name:string;key:string;label:string;metrics:PackMetric[];defaultDimensions:Semantic[];keyMetrics:string[];thresholds?:Record<string,number>;rules:SemanticRule[];signals:Semantic[];minSignals:number;priority:number;kpis:KpiDef[];trend:{title:string;subtitle:string};composition:CompositionDef;ranking:RankSectionDef;secondary:RankSectionDef;}
const sumRevenue=(r:Row[],s:SchemaMap)=>r.reduce((a,x)=>a+A.rowRevenue(x,s),0),sumProfit=(r:Row[],s:SchemaMap)=>r.reduce((a,x)=>a+A.rowProfit(x,s),0),distinct=(sem:Semantic)=>(r:Row[],s:SchemaMap)=>s[sem]?new Set(r.map(x=>A.str(x[s[sem]!])).filter(Boolean)).size:0,distinctOrCount=(sem:Semantic)=>(r:Row[],s:SchemaMap)=>s[sem]?new Set(r.map(x=>A.str(x[s[sem]!])).filter(Boolean)).size:r.length,distinctCustomers=(r:Row[],s:SchemaMap)=>(s.customer_id?distinct("customer_id"):distinct("customer_name"))(r,s),marginPct=(r:Row[],s:SchemaMap)=>{const rev=sumRevenue(r,s);return rev?sumProfit(r,s)/rev*100:0;};
const builtinMetrics:PackMetric[]=[{id:"revenue",label:"Revenue",kind:"sum",format:"money",builtin:true,words:["revenue","sales","income","turnover","gross"],compute:sumRevenue},{id:"profit",label:"Profit",kind:"sum",format:"money",builtin:true,words:["profit","margin","earnings","net income","net"],compute:sumProfit},{id:"quantity",label:"Quantity",kind:"sum",format:"number",builtin:true,words:["quantity","units","volume","items sold","count"],compute:(r,s)=>r.reduce((a,x)=>a+(s.quantity?A.num(x[s.quantity]):1),0)},{id:"orders",label:"Orders",kind:"distinct",format:"number",builtin:true,words:["orders","order","transactions","invoices"],compute:(r,s)=>s.order_id?new Set(r.map(x=>A.str(x[s.order_id!]))).size:r.length}];
const saasMetrics:PackMetric[]=[{id:"mrr",label:"MRR",kind:"sum",format:"money",words:["mrr","monthly recurring","recurring revenue","subscription revenue"],compute:(r,s)=>{const c=r[0]?Object.keys(r[0]).find(k=>/^mrr$|monthly.*recurr|subscription.*revenue/i.test(k)):undefined;return c?r.reduce((a,x)=>a+A.num(x[c]),0):sumRevenue(r,s);}},{id:"churn",label:"Churn",kind:"ratio",format:"percent",words:["churn","cancellations","lost customers","attrition"],compute:(r,s)=>{if(!s.date||!s.customer_id)return 0;const d=r.map(x=>({r:x,d:A.parseDate(x[s.date!])})).filter(x=>x.d) as {r:Row;d:Date}[];if(d.length<4)return 0;d.sort((a,b)=>a.d.getTime()-b.d.getTime());const mid=d[Math.floor(d.length/2)].d.getTime(),first=d.filter(x=>x.d.getTime()<mid),second=d.filter(x=>x.d.getTime()>=mid),ids=new Set(first.map(x=>A.str(x.r[s.customer_id!]))),churned=[...ids].filter(id=>!second.some(x=>A.str(x.r[s.customer_id!])===id)).length;return ids.size?Math.round(churned/ids.size*1000)/10:0;}},{id:"arpu",label:"ARPU",kind:"ratio",format:"money",words:["arpu","average revenue per user","average revenue per customer","per customer","per user"],compute:(r,s)=>{const rev=sumRevenue(r,s),c=s.customer_id?new Set(r.map(x=>A.str(x[s.customer_id!]))).size:s.customer_name?new Set(r.map(x=>A.str(x[s.customer_name!]))).size:0;return c?Math.round(rev/c*100)/100:0;}}];
const pharmacyMetrics:PackMetric[]=[{id:"expiry_risk",label:"Expiry Risk",kind:"ratio",format:"percent",words:["expiry","expiring","expiration","about to expire","expiring soon"],compute:(r,s)=>{const c=r[0]?Object.keys(r[0]).find(k=>/expir|expiry/i.test(k)):undefined;if(!c||!r.length||!s.date)return 0;const ds=r.map(x=>A.parseDate(x[s.date!])).filter(Boolean) as Date[];if(!ds.length)return 0;const latest=Math.max(...ds.map(d=>d.getTime()));const risk=r.filter(x=>{const d=A.parseDate(x[c]);return !!d&&d.getTime()<=latest&&d.getTime()>=latest-90*86_400_000;}).length;return Math.round(risk/r.length*1000)/10;}}];
const servicesMetrics:PackMetric[]=[{id:"utilization",label:"Utilization",kind:"ratio",format:"percent",words:["utilization","billable","utilised","utilized","capacity"],compute:r=>{const b=r[0]?Object.keys(r[0]).find(k=>/billable/i.test(k)):undefined,t=r[0]?Object.keys(r[0]).find(k=>/^hours?$|total.*hours/i.test(k)):undefined;if(!b||!t)return 0;const bv=r.reduce((a,x)=>a+A.num(x[b]),0),tv=r.reduce((a,x)=>a+A.num(x[t]),0);return tv?Math.round(bv/tv*1000)/10:0;}},{id:"avg_rate",label:"Avg Rate",kind:"ratio",format:"money",words:["rate","hourly rate","billing rate","per hour"],compute:(r,s)=>{const b=r[0]?Object.keys(r[0]).find(k=>/billable/i.test(k)):undefined;if(!b)return 0;const h=r.reduce((a,x)=>a+A.num(x[b]),0);return h?Math.round(sumRevenue(r,s)/h*100)/100:0;}}];
const manufacturingMetrics:PackMetric[]=[{id:"defect_rate",label:"Defect Rate",kind:"ratio",format:"percent",words:["defect","defective","rework","scrap","quality"],compute:(r,s)=>{const c=r[0]?Object.keys(r[0]).find(k=>/defect|rework|scrap/i.test(k)):undefined;if(!c)return 0;const defects=r.reduce((a,x)=>a+A.num(x[c]),0),total=s.quantity?r.reduce((a,x)=>a+A.num(x[s.quantity!]),0):r.length;return total?Math.round(defects/total*1000)/10:0;}}];
const retailRules:SemanticRule[]=[];const pharmacyRules:SemanticRule[]=[{semantic:"prescription_id",patterns:[/prescription/,/rx[_ ]?(no|id)/,/^rx$/]},{semantic:"medicine_name",patterns:[/medicine/,/drug/,/^med(icine)?[_ ]?name$/,/^med$/]},{semantic:"patient_id",patterns:[/patient/,/^mrn$/]},{semantic:"revenue",patterns:[/bill[_ ]?amount/,/total[_ ]?price/,/net[_ ]?amount/,/amount/]}];const saasRules:SemanticRule[]=[{semantic:"subscription_id",patterns:[/subscription/,/^sub[_ ]?id/]},{semantic:"plan",patterns:[/plan/,/tier/,/^package$/]},{semantic:"revenue",patterns:[/mrr/,/arr/,/monthly[_ ]?recurring/,/recurring[_ ]?revenue/,/amount/]},{semantic:"customer_name",patterns:[/account[_ ]?name/,/^account$/,/company/,/^org(anization)?$/]},{semantic:"customer_id",patterns:[/account[_ ]?id/,/^user[_ ]?id$/]}];const servicesRules:SemanticRule[]=[{semantic:"customer_name",patterns:[/client/,/customer/]},{semantic:"department",patterns:[/service[_ ]?line/,/practice/]},{semantic:"date",patterns:[/work[_ ]?date/,/service[_ ]?date/]},{semantic:"revenue",patterns:[/revenue/,/billing/,/billings/]},{semantic:"quantity",patterns:[/billable[_ ]?hours/,/hours/] }];const manufacturingRules:SemanticRule[]=[{semantic:"product_name",patterns:[/product/,/sku/]},{semantic:"quantity",patterns:[/units/,/quantity/,/produced/]},{semantic:"date",patterns:[/production[_ ]?date/,/manufacture[_ ]?date/,/date/]},{semantic:"category",patterns:[/line/,/machine/,/plant/]},{semantic:"revenue",patterns:[/revenue/,/sales/] }];
function kpis():KpiDef[]{return[{key:"revenue",label:"Revenue",icon:"revenue",format:"money",value:sumRevenue},{key:"profit",label:"Profit",icon:"profit",format:"money",value:sumProfit},{key:"orders",label:"Orders",icon:"orders",format:"number",value:distinctOrCount("order_id")},{key:"customers",label:"Customers",icon:"customers",format:"number",value:distinctCustomers},{key:"margin",label:"Margin",icon:"margin",format:"percent",noChange:true,value:marginPct}];}
function makePack(id:string,name:string,metrics:PackMetric[],rules:SemanticRule[],signals:Semantic[],defaults:Semantic[],keyMetrics:string[],thresholds:Record<string,number>):IndustryPack{const kk=kpis();return{id,name,key:id,label:name,metrics,defaultDimensions:defaults,keyMetrics,thresholds,rules,signals,minSignals:id==="generic"?Infinity:2,priority:id==="generic"?-1:10,kpis:kk,trend:{title:"Performance Overview",subtitle:"Revenue & profit over time"},composition:{dimension:"category",fallback:"region",title:"Revenue Composition",subtitle:"Share by category",centerLabel:"Revenue"},ranking:{dimension:"product_name",metric:"revenue",title:"Top Products",subtitle:"Ranked by revenue",emptyText:"No product column detected",format:"money",limit:8},secondary:{dimension:"region",metric:"revenue",title:"Region Performance",subtitle:"By revenue",emptyText:"No region column detected",format:"money",limit:10}};}
const genericPack=makePack("generic","Generic",builtinMetrics,[],[],["product_name","customer_name","region","category","department"],["revenue","profit","orders"],{revenue:-5,profit_margin:10});const retailPack=makePack("retail","Retail",builtinMetrics,retailRules,["order_id","product_name","region","category"],["product_name","customer_name","region","category","state","department"],["revenue","profit","orders"],{revenue:-5,profit_margin:10});const saasPack=makePack("saas","SaaS",[...builtinMetrics,...saasMetrics],saasRules,["subscription_id","plan"],["customer_name","product_name","region","category"],["mrr","churn","arpu","revenue"],{churn:5,revenue:-10,arpu:-10});const pharmacyPack=makePack("pharmacy","Pharmacy",[...builtinMetrics,...pharmacyMetrics],pharmacyRules,["prescription_id","medicine_name","patient_id"],["product_name","category","region","department"],["revenue","expiry_risk","profit"],{expiry_risk:5,revenue:-5});const servicesPack=makePack("services","Services",[...builtinMetrics,...servicesMetrics],servicesRules,["billable_hours","total_hours"],["customer_name","product_name","category","region","department"],["revenue","utilization","avg_rate"],{utilization:60,revenue:-5});const manufacturingPack=makePack("manufacturing","Manufacturing",[...builtinMetrics,...manufacturingMetrics],manufacturingRules,["defect","production","machine"],["product_name","category","region","state","department"],["revenue","defect_rate","profit"],{defect_rate:2,revenue:-5});
export const PACKS:Record<string,IndustryPack>={generic:genericPack,retail:retailPack,saas:saasPack,pharmacy:pharmacyPack,services:servicesPack,manufacturing:manufacturingPack};export const DEFAULT_PACK_ID="generic";export const INDUSTRIES=Object.values(PACKS).map(p=>({key:p.id,label:p.name}));export function getPack(id?:string|null):IndustryPack{return(id&&PACKS[id])||genericPack;}export function packMetrics(pack:IndustryPack){return pack.metrics;}export function packMetric(pack:IndustryPack,id:string){return pack.metrics.find(m=>m.id===id);}
export function resolveMetricFromWords(pack:IndustryPack,q:string):PackMetric|undefined{const lower=q.toLowerCase();const words=pack.metrics.flatMap(m=>m.words.map(w=>({m,w}))).sort((a,b)=>b.w.length-a.w.length);for(const{m,w}of words){const escaped=w.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");if(new RegExp(`\\b${escaped}\\b`,"i").test(lower))return m;}return undefined;}
export function detectPack(s:SchemaMap,columns:string[]=[],datasetName=""):IndustryPack{const words=`${datasetName} ${[...columns,...Object.values(s)].join(" ")}`.toLowerCase();if(/monthly recurring|subscription|churn|plan|license seat|seat/.test(words))return saasPack;if(/prescription|pharmacy|drug|medication|expiry/.test(words))return pharmacyPack;if(/billable|timesheet|utilization|consulting|service level/.test(words))return servicesPack;if(/defect|rework|scrap|production|batch|machine|shift/.test(words))return manufacturingPack;if(/customer|order|product|category|region|retail|store/.test(words))return retailPack;return genericPack;}
export function suggestIndustry(columns:ColumnProfile[]):string{const ranked=Object.values(PACKS).filter(p=>p.signals.length).map(p=>({p,score:p.signals.filter(s=>detectSchema(columns,p.rules).map[s]).length})).filter(x=>x.score>=x.p.minSignals).sort((a,b)=>b.score-a.score||b.p.priority-a.p.priority);return ranked[0]?.p.id??"generic";}
