import type { Row } from "./parse.js";
import type { SchemaMap, Semantic } from "./schema.js";
import * as A from "./analytics.js";
import { forecast } from "./forecast.js";
import { detectPack, getPack, packMetric } from "./industries.js";
import { investigate } from "./investigate.js";
export interface Recommendation{title:string;observation:string;explanation:string;action:string;impact:"LOW"|"MEDIUM"|"HIGH";confidence:number;}
export interface AlertSeed{type:string;severity:"LOW"|"MEDIUM"|"HIGH";metric:string;currentValue:number|null;threshold:number|null;description:string;}
export function deriveInsights(rows:Row[],s:SchemaMap,packId?:string){const pack=packId?getPack(packId):detectPack(s,[],"");const ov=A.overview(rows,s),recs:Recommendation[]=[],alerts:AlertSeed[]=[];
for(const id of pack.keyMetrics){const metric=packMetric(pack,id);if(!metric)continue;const series=A.timeSeries(rows,s,metric);if(series.length<2)continue;const prev=series[series.length-2].value,cur=series[series.length-1].value;if(prev>0){const changePct=Math.round((cur-prev)/Math.abs(prev)*1000)/10,thresh=pack.thresholds?.[id]??-10;if(changePct<=thresh){const severity=changePct<=thresh*2?"HIGH":"MEDIUM";alerts.push({type:`${id}_drop`,severity,metric:id,currentValue:cur,threshold:prev,description:`${metric.label} fell ${Math.abs(changePct)}% in the latest period.`});recs.push({title:`${metric.label} is declining`,observation:`${metric.label} changed ${changePct}% period-over-period (${money(prev)} → ${money(cur)}).`,explanation:"Possible causes include demand shifts, pricing, inventory, or segment weakness. These are hypotheses, not confirmed causes.",action:`Investigate the largest ${metric.label.toLowerCase()} contributors by the pack's key dimensions.`,impact:severity==="HIGH"?"HIGH":"MEDIUM",confidence:.7});}else if(changePct>=15)alerts.push({type:`${id}_spike`,severity:"LOW",metric:id,currentValue:cur,threshold:prev,description:`${metric.label} grew ${changePct}% in the latest period.`});}}
const dropped=pack.keyMetrics.map(id=>({id,metric:packMetric(pack,id)})).find(x=>{if(!x.metric)return false;const ts=A.timeSeries(rows,s,x.metric);if(ts.length<2)return false;const p=ts[ts.length-2].value,c=ts[ts.length-1].value;return p>0&&Math.round((c-p)/Math.abs(p)*1000)/10<=(pack.thresholds?.[x.id]??-10);});if(dropped?.metric){const inv=investigate(rows,s,dropped.id,pack.id);recs.push({title:`Why is ${dropped.metric.label} changing?`,observation:inv.narrative,explanation:"Evidence-backed investigation; correlation is association, not cause.",action:"Review the cited dimensions and factors and validate with a controlled experiment.",impact:"HIGH",confidence:.65});}
if(ov.profitMargin<10&&ov.revenue.value>0){alerts.push({type:"profit_decline",severity:ov.profitMargin<0?"HIGH":"MEDIUM",metric:"profit_margin",currentValue:ov.profitMargin,threshold:10,description:`Profit margin is ${ov.profitMargin}%, below a healthy 10% threshold.`});recs.push({title:"Thin profit margins",observation:`Overall profit margin is ${ov.profitMargin}% on ${money(ov.revenue.value)} revenue.`,explanation:"Low margins can stem from high cost of goods, discounting, or an unfavourable product mix.",action:"Review pricing on low-margin categories and supplier costs.",impact:"MEDIUM",confidence:.65});}
const decliners=changeByGroup(rows,s);if(decliners.length){recs.push({title:"Products in decline",observation:`${decliners.slice(0,3).map(d=>`${d.label} (${d.changePct}%)`).join(", ")} show falling revenue across periods.`,explanation:"Declines may reflect product life-cycle, competition, or stock issues.",action:"Investigate these products.",impact:"MEDIUM",confidence:.6});alerts.push({type:"unusual_performance",severity:"MEDIUM",metric:"revenue",currentValue:null,threshold:null,description:`${decliners.length} groups show declining revenue.`});}
if(s.inventory){const low=lowInventory(rows,s);if(low.length){alerts.push({type:"inventory_shortage",severity:"MEDIUM",metric:"inventory",currentValue:low.length,threshold:20,description:`${low.length} products are below 20 units of inventory.`});recs.push({title:"Inventory shortage risk",observation:`${low.length} products have inventory below 20 units.`,explanation:"Low stock risks lost revenue from stockouts.",action:"Reorder at-risk products, prioritising high-revenue items.",impact:"HIGH",confidence:.75});}}
const primary=packMetric(pack,pack.keyMetrics[0]??"revenue")??packMetric(pack,"revenue");if(primary){const ts=A.timeSeries(rows,s,primary);if(ts.length>=3){const fc=forecast(ts.map(p=>({period:p.period,value:p.value})),1),next=fc.points[0];if(next&&next.value<ts[ts.length-1].value*.9)alerts.push({type:"forecast_risk",severity:"MEDIUM",metric:primary.id,currentValue:next.value,threshold:ts[ts.length-1].value,description:`Forecast projects ${primary.label} of ${money(next.value)} next period.`});}}
const risers=growingGroups(rows,s);if(risers.length)recs.push({title:"Growth opportunity",observation:`${risers[0].label} grew ${risers[0].changePct}% — the fastest-growing segment.`,explanation:"A concentrated growth area can justify targeted investment.",action:`Consider increasing inventory and marketing for ${risers[0].label}.`,impact:"MEDIUM",confidence:.6});return{recommendations:recs,alerts};}
function halfSplit(rows:Row[],s:SchemaMap){if(!s.date)return{first:[],second:[]};const d=rows.map(r=>({r,d:A.parseDate(r[s.date!])})).filter(x=>x.d) as {r:Row;d:Date}[];d.sort((a,b)=>a.d.getTime()-b.d.getTime());if(!d.length)return{first:[],second:[]};const mid=d[Math.floor(d.length/2)].d.getTime(),first:Row[]=[],second:Row[]=[];for(const x of d)(x.d.getTime()<mid?first:second).push(x.r);return{first,second};}
export function changeByGroup(rows:Row[],s:SchemaMap,dimOverride?:Semantic){const dim=dimOverride??(s.product_name?"product_name":s.category?"category":s.region?"region":null);if(!dim)return[];const{first,second}=halfSplit(rows,s);if(!first.length||!second.length)return[];const a=new Map(A.groupBy(first,s,dim,"revenue",{},100).map(x=>[x.label,x.value])),b=new Map(A.groupBy(second,s,dim,"revenue",{},100).map(x=>[x.label,x.value])),out:{label:string;changePct:number}[]=[];for(const[label,bv]of b){const av=a.get(label)??0;if(av>0)out.push({label,changePct:Math.round((bv-av)/av*1000)/10});}return out;}
function decliningGroups(rows:Row[],s:SchemaMap){return changeByGroup(rows,s).filter(x=>x.changePct<=-10).sort((a,b)=>a.changePct-b.changePct);} function growingGroups(rows:Row[],s:SchemaMap){return changeByGroup(rows,s).filter(x=>x.changePct>=10).sort((a,b)=>b.changePct-a.changePct);} function lowInventory(rows:Row[],s:SchemaMap){const inv=new Map<string,number>(),key=s.product_name||s.category;if(!key||!s.inventory)return[];for(const r of rows){const p=A.str(r[key]);inv.set(p,Math.min(inv.get(p)??Infinity,A.num(r[s.inventory!])));}return[...inv.entries()].map(([label,value])=>({label,value})).filter(x=>x.value<20).sort((a,b)=>a.value-b.value);} const money=A.fmtMoney;
