import type { Row } from "./parse.js";
import type { SchemaMap, Semantic } from "./schema.js";
import * as A from "./analytics.js";
import { forecast } from "./forecast.js";
import { changeByGroup } from "./insights.js";
import { detectPack, getPack, resolveMetricFromWords, type IndustryPack, type PackMetric } from "./industries.js";
import { investigate } from "./investigate.js";

export interface Intent { intent:string; metrics:string[]; dimensions:string[]; filters:Record<string,string>; limit:number; visualization:"bar"|"line"|"table"|"kpi"|"none"; question?:string; }
export interface ChatResult { intent:Intent; explanation:string; table?:{columns:string[];rows:(string|number)[][]}; chart?:{type:"bar"|"line";data:{label:string;value:number}[];xKey:string;yKey:string}; metrics?:{label:string;value:number}[]; confidence:number; }
function wordMatch(word:string):RegExp{return new RegExp(`\\b${word}\\b`,"i");}
const DIM_WORDS:Record<string,Semantic>={customer:"customer_name",customers:"customer_name",client:"customer_name",product:"product_name",products:"product_name",item:"product_name",region:"region",regions:"region",state:"state",states:"state",category:"category",categories:"category",department:"department",month:"date",monthly:"date",time:"date",trend:"date"};
function pickDimension(q:string):Semantic|null{for(const[w,d]of Object.entries(DIM_WORDS))if(wordMatch(w).test(q))return d;return null;}
function pickLimit(q:string,def=10){const m=/top\s+(\d+)|(\d+)\s+(customers|products|regions|items)/.exec(q);const n=m?Number(m[1]||m[2]):def;return Math.min(50,Math.max(1,n||def));}
function pickMetric(q:string,s:SchemaMap,pack:IndustryPack):PackMetric{const hit=resolveMetricFromWords(pack,q);if(hit)return hit;if(s.revenue||s.sales)return pack.metrics.find(m=>m.id==="revenue")!;return pack.metrics.find(m=>m.id==="orders")!;}
function metricLabel(m:PackMetric){return m.label;}
export const INTENTS=["top_n","trend","max_period","min_period","forecast","explain_change","growing_groups","declining_groups","inventory_risk","unknown"] as const;
export const METRICS=["revenue","profit","quantity","orders"] as const;

export function ruleParse(question:string,s:SchemaMap):Intent{const q=question.toLowerCase(),pack=detectPack(s,[],""),m=pickMetric(q,s,pack);let intent="top_n",dims:Semantic[]=[];if(/predict|forecast|next month|next quarter|projection|will be/.test(q)){intent="forecast";dims=["date"];}else if(/why|reason|cause/.test(q)){intent="explain_change";dims=["date"];}else if(/declin|falling|dropping|grow|rising|fastest|climbing/.test(q)){intent=/grow|rising|fastest|climbing/.test(q)?"growing_groups":"declining_groups";const d=pickDimension(q)??(s.product_name?"product_name":s.region?"region":null);if(d)dims=[d];}else if(/highest|lowest|best|worst/.test(q)){intent=/lowest|worst/.test(q)?"min_period":"max_period";dims=["date"];}else{const d=pickDimension(q);if(d=== "date"){intent="trend";dims=["date"];}else if(d)dims=[d];}return{intent,metrics:[m.id],dimensions:dims,filters:{},limit:pickLimit(q),visualization:intent==="forecast"||intent==="trend"?"line":"bar",question};}
export function runIntent(intent:Intent,rows:Row[],s:SchemaMap):ChatResult{const q=intent.question??`${intent.intent.replace(/_/g," ")} ${intent.metrics[0]??"revenue"} ${intent.dimensions[0]&&intent.dimensions[0]!=="date"?intent.dimensions[0]:""}`;return answer(q,rows,s);}

export function answer(question:string,rows:Row[],s:SchemaMap,packId?:string):ChatResult{const q=question.toLowerCase(),pack=packId?getPack(packId):detectPack(s,[],""),metric=pickMetric(q,s,pack);
if(/predict|forecast|next month|next quarter|projection|will be/.test(q)){const series=A.timeSeries(rows,s,metric);if(series.length<2)return fallback(question,"Not enough time-based history to forecast.");const fc=forecast(series.map(p=>({period:p.period,value:p.value})),3),next=fc.points[0];return{intent:{intent:"forecast",metrics:[metric.id],dimensions:["date"],filters:{},limit:3,visualization:"line",question},explanation:`Projected ${metricLabel(metric)} for ${next.period} is ~${fmt(next.value)} (range ${fmt(next.lower)}–${fmt(next.upper)}), based on the recent trend. This is an estimate, not a guarantee.`,chart:{type:"line",xKey:"label",yKey:"value",data:[...series.map(p=>({label:p.period,value:p.value})),...fc.points.map(p=>({label:p.period,value:p.value}))]},metrics:fc.points.map(p=>({label:p.period,value:p.value})),confidence:.6};}
if(/(which|what).*(month|period|day).*(highest|most|best|top|lowest|worst|least)/.test(q)||/(highest|lowest|best|worst).*(month|quarter|week|day|period)/.test(q)){const series=A.timeSeries(rows,s,metric);if(!series.length)return fallback(question,"No date column detected to analyse by month.");const worst=/lowest|worst|least/.test(q),best=[...series].sort((x,y)=>worst?x.value-y.value:y.value-x.value)[0];return{intent:{intent:worst?"min_period":"max_period",metrics:[metric.id],dimensions:["date"],filters:{},limit:1,visualization:"bar",question},explanation:`${best.period} had the ${worst?"lowest":"highest"} ${metricLabel(metric)}: ${fmt(best.value)}.`,chart:{type:"bar",xKey:"label",yKey:"value",data:series.map(p=>({label:p.period,value:p.value}))},metrics:[{label:best.period,value:best.value}],confidence:.9};}
if(/why|reason|cause/.test(q)){const inv=investigate(rows,s,metric.id,pack.id),series=A.timeSeries(rows,s,metric);return{intent:{intent:"explain_change",metrics:[metric.id],dimensions:["date"],filters:{},limit:5,visualization:"line",question},explanation:inv.narrative,chart:series.length?{type:"line",xKey:"label",yKey:"value",data:series.map(p=>({label:p.period,value:p.value}))}:undefined,metrics:inv.claims.slice(0,5).map(c=>({label:c.detail,value:c.value})),confidence:.6};}
if(/declin|falling|dropping|grow(ing)?|rising|fastest|climbing|surging/.test(q)){const growth=/grow|rising|fastest|climbing|surging/.test(q),dim=pickDimension(q)??(s.product_name?"product_name":s.region?"region":s.customer_name?"customer_name":null);if(!dim||dim==="date"||!s.date)return fallback(question,"Need a date column plus a grouping dimension to compare periods.");const changes=changeByGroup(rows,s,dim).sort((a,b)=>growth?b.changePct-a.changePct:a.changePct-b.changePct),picked=(growth?changes.filter(c=>c.changePct>0):changes.filter(c=>c.changePct<0)).slice(0,10),label=dim.replace("_name","").replace("_"," ");return{intent:{intent:growth?"growing_groups":"declining_groups",metrics:[metric.id],dimensions:[dim],filters:{},limit:picked.length,visualization:"bar",question},explanation:picked.length?`${picked.length} ${label}s ${growth?"grew":"declined"}.`:`No clear ${growth?"growth":"decline"} was found.`,chart:picked.length?{type:"bar",xKey:"label",yKey:"value",data:picked.map(p=>({label:p.label,value:p.changePct}))}:undefined,table:picked.length?{columns:[cap(label),"Change %"],rows:picked.map(p=>[p.label,p.changePct])}:undefined,confidence:.65};}
if(/inventory|stock/.test(q)&&s.inventory){const inv=new Map<string,number>();for(const r of rows){const p=A.str(s.product_name?r[s.product_name]:r[s.category!]);inv.set(p,Math.min(inv.get(p)??Infinity,A.num(r[s.inventory!])));}const low=[...inv.entries()].map(([label,value])=>({label,value})).sort((a,b)=>a.value-b.value).slice(0,10);return{intent:{intent:"inventory_risk",metrics:["inventory"],dimensions:["product_name"],filters:{},limit:10,visualization:"table",question},explanation:`${low.filter(x=>x.value<20).length} products are below the inventory threshold.`,table:{columns:["Product","Min inventory"],rows:low.map(x=>[x.label,x.value])},confidence:.75};}
const dim=pickDimension(q)??(s.customer_name?"customer_name":s.product_name?"product_name":"region");if(dim==="date"){const series=A.timeSeries(rows,s,metric);return{intent:{intent:"trend",metrics:[metric.id],dimensions:["date"],filters:{},limit:series.length,visualization:"line",question},explanation:`${metricLabel(metric)} over time, by month.`,chart:{type:"line",xKey:"label",yKey:"value",data:series.map(p=>({label:p.period,value:p.value}))},confidence:.85};}const ranked=A.groupBy(rows,s,dim,metric,{},pickLimit(q));if(!ranked.length)return fallback(question,"I couldn't map that question to the columns in this dataset.");const dl=dim.replace("_name","").replace("_"," ");return{intent:{intent:"top_n",metrics:[metric.id],dimensions:[dim],filters:{},limit:ranked.length,visualization:"bar",question},explanation:`Top ${ranked.length} ${dl}s by ${metricLabel(metric)}. Leader: ${ranked[0].label} (${fmt(ranked[0].value)}).`,chart:{type:"bar",xKey:"label",yKey:"value",data:ranked},table:{columns:[cap(dl),metricLabel(metric)],rows:ranked.map(r=>[r.label,r.value])},confidence:.8};}
function fallback(_question:string,msg:string):ChatResult{return{intent:{intent:"unknown",metrics:[],dimensions:[],filters:{},limit:0,visualization:"none"},explanation:`${msg} Try questions like "top 10 customers" or "predict next month's revenue".`,confidence:.2};}
function fmt(n:number){const v=A.num(n);return Math.abs(v)>=1000?v.toLocaleString(undefined,{maximumFractionDigits:0}):String(Math.round(v*100)/100);}
function cap(s:string){return s.charAt(0).toUpperCase()+s.slice(1);}
