import OpenAI from "openai";
import { z } from "zod";
import { env } from "../env.js";
import type { SchemaMap } from "../engine/schema.js";
import { INTENTS, type Intent } from "../engine/intent.js";
const client=env.openaiApiKey?new OpenAI({apiKey:env.openaiApiKey,timeout:12000,maxRetries:1}):null;
const Emitted=z.object({intent:z.enum(INTENTS),metric:z.string().min(1).max(80),dimension:z.string(),limit:z.number().int().min(1).max(50)});
const intentSchema={type:"object",properties:{intent:{type:"string",enum:[...INTENTS],description:"The analytics operation the question asks for."},metric:{type:"string",description:"The metric named by the user, such as revenue, MRR, churn, ARPU, expiry risk, utilization, or defect rate."},dimension:{type:"string",description:"The grouping column: a listed dimension, date, or none."},limit:{type:"integer",minimum:1,maximum:50,description:"How many rows to return."}},required:["intent","metric","dimension","limit"],additionalProperties:false} as const;
function schemaSummary(s:SchemaMap){const dims=(Object.keys(s) as Array<keyof SchemaMap>).filter(d=>d!=="date"&&!!s[d]).map(String);const cols=Object.entries(s).map(([semantic,col])=>`- ${semantic} (column "${col}")`).join("\n");return{text:`The dataset has these business columns:\n${cols}\n\nAvailable grouping dimensions: ${dims.join(", ")||"none"}${s.date?", date":""}.`,dimensions:dims};}
const SYSTEM=`Translate a business question into one structured analytics intent. You never see data rows. Preserve the user's metric wording exactly when possible; the deterministic engine resolves it against the active industry pack. Supported intents: top_n, trend, max_period, min_period, forecast, explain_change, growing_groups, declining_groups, inventory_risk, unknown. Choose only a usable grouping dimension.`;
export async function llmParseIntent(question:string,schema:SchemaMap):Promise<Intent|null>{if(!client)return null;const summary=schemaSummary(schema);try{const res=await client.chat.completions.create({model:env.aiModel,messages:[{role:"system",content:SYSTEM},{role:"user",content:`${summary.text}\n\nQuestion: ${question}`}],response_format:{type:"json_schema",json_schema:{name:"analytics_intent",strict:true,schema:intentSchema}}});const msg=res.choices[0]?.message;if(!msg||msg.refusal||!msg.content)return null;const e=Emitted.parse(JSON.parse(msg.content));const dim=e.dimension==="date"||summary.dimensions.includes(e.dimension)?e.dimension:null;return{intent:e.intent,metrics:[e.metric],dimensions:dim?[dim]:[],filters:{},limit:e.limit,visualization:"none",question};}catch{return null;}}
